[workspace]
members = [
  "irmaseal-core",
  "irmaseal-cli",
  "irmaseal-pkg",
  "irmaseal-wasm-bindings"
]

resolver = "2"

[profile.release] 
lto = true

[profile.release.package.irmaseal-wasm-bindings]
opt-level = "s"
