on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Continuous integration

jobs:
  build-core:
    name: Build core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          args: --manifest-path irmaseal-core/Cargo.toml --all-features
          command: build

  build-pkg:
    name: Build pkg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          args: --manifest-path irmaseal-pkg/Cargo.toml
          command: build

  build-cli:
    name: Build CLI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          args: --manifest-path irmaseal-cli/Cargo.toml
          command: build

  test-core:
    name: Test core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          args: --manifest-path irmaseal-core/Cargo.toml --all-features
          command: test

  fmt-core:
    name: Format core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          args: --manifest-path irmaseal-core/Cargo.toml --all -- --check
          command: fmt

  fmt-pkg:
    name: Format pkg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          args: --manifest-path irmaseal-pkg/Cargo.toml --all -- --check
          command: fmt

  fmt-cli:
    name: Format CLI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          args: --manifest-path irmaseal-cli/Cargo.toml --all -- --check
          command: fmt

  test-wasm-bindings-chrome:
    name: Run wasm tests in Google Chrome
    runs-on: ubuntu-latest
    env:
      WASM_BINDGEN_TEST_TIMEOUT: 120
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: wasm-pack test --headless --chrome ./irmaseal-wasm-bindings

  test-wasm-bindings-safari:
    name: Run wasm tests in Safari
    runs-on: macos-latest
    env:
      WASM_BINDGEN_TEST_TIMEOUT: 120
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: wasm-pack test --headless --safari ./irmaseal-wasm-bindings

  test-wasm-bindings-firefox:
    name: Run wasm tests in Mozilla Firefox
    runs-on: ubuntu-latest
    env:
      WASM_BINDGEN_TEST_TIMEOUT: 120
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: sudo apt update && sudo apt install firefox
      - run: wasm-pack test --headless --firefox ./irmaseal-wasm-bindings
